### ISSUE TITLE
temporal-csound-0.4.1 does not compile

### ISSUE THREAD

**Issue by peti** [anton-k/temporal-csound#2]
A complete build log is at http://hydra.cryp.to/build/558516/nixlog/1/raw. I believe that the build was broken by an update of one of the code's dependencies.

**Comment by anton-k** [comment]
Yes, you are right. I've changed the midi functions. Signature is slightly changed. But I forgot to update the temporal-csound package

**Comment by anton-k** [comment]
fixed
